2023-04-08 21:57:44,057 INFO: Bet Brasileirão startup [in C:\Users\fenix\Documents\quiz_bet_br\bet\__init__.py:74]
2023-04-08 21:58:57,016 INFO: Bet Brasileirão startup [in C:\Users\fenix\Documents\quiz_bet_br\bet\__init__.py:74]
2023-04-08 22:16:00,858 INFO: Bet Brasileirão startup [in C:\Users\fenix\Documents\quiz_bet_br\bet\__init__.py:74]
2023-04-09 00:40:20,201 INFO: Bet Brasileirão startup [in C:\Users\fenix\Documents\quiz_bet_br\bet\__init__.py:74]
2023-04-09 00:40:59,800 INFO: Bet Brasileirão startup [in C:\Users\fenix\Documents\quiz_bet_br\bet\__init__.py:74]
2023-04-09 00:42:35,686 INFO: Bet Brasileirão startup [in C:\Users\fenix\Documents\quiz_bet_br\bet\__init__.py:74]
2023-04-09 00:43:33,888 INFO: Bet Brasileirão startup [in C:\Users\fenix\Documents\quiz_bet_br\bet\__init__.py:74]
2023-04-09 00:43:34,112 ERROR: Exception on /quiz [GET] [in C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\fenix\Documents\quiz_bet_br\bet\main\routes.py", line 167, in quiz
    return render_template('_quiz.html', form=form, question=question)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\fenix\Documents\quiz_bet_br\bet\templates\_quiz.html", line 2, in <module>
    {% extends "base.html" %}
  File "C:\Users\fenix\Documents\quiz_bet_br\bet\templates\base.html", line 1, in <module>
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in <module>
    {% block doc -%}
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in <module>
    {%- block html %}
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in <module>
    {% block body -%}
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in <module>
    {% block content -%}
  File "C:\Users\fenix\Documents\quiz_bet_br\bet\templates\_quiz.html", line 7, in <module>
    <form method="POST" action="{{ url_for('bp.quiz') }}">
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'bp.quiz'. Did you mean 'main.quiz' instead?
2023-04-09 00:43:36,735 ERROR: Exception on /quiz [GET] [in C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\fenix\Documents\quiz_bet_br\bet\main\routes.py", line 167, in quiz
    return render_template('_quiz.html', form=form, question=question)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\fenix\Documents\quiz_bet_br\bet\templates\_quiz.html", line 2, in <module>
    {% extends "base.html" %}
  File "C:\Users\fenix\Documents\quiz_bet_br\bet\templates\base.html", line 1, in <module>
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in <module>
    {% block doc -%}
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in <module>
    {%- block html %}
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in <module>
    {% block body -%}
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in <module>
    {% block content -%}
  File "C:\Users\fenix\Documents\quiz_bet_br\bet\templates\_quiz.html", line 7, in <module>
    <form method="POST" action="{{ url_for('bp.quiz') }}">
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'bp.quiz'. Did you mean 'main.quiz' instead?
2023-04-09 00:46:39,573 INFO: Bet Brasileirão startup [in C:\Users\fenix\Documents\quiz_bet_br\bet\__init__.py:74]
2023-04-09 00:46:43,939 ERROR: Exception on / [GET] [in C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\fenix\Documents\quiz_bet_br\bet\main\routes.py", line 46, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\fenix\Documents\quiz_bet_br\.myenv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\fenix\Documents\quiz_bet_br\bet\templates\index.html", line 540, in <module>
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
